Repository SpiNNakerManchester/PyNNExamples, pull requests merged in 2020-12, with the labels that each got.

#41 examples for self partitioning idea
  examples/partitioner_examples/__init__.py
  examples/partitioner_examples/splitter_usage.py
Labels: enhancement, in progress

#51 fixed examples
  examples/extra_models_examples/vogel_2011/spynnaker.cfg
  examples/partitioner_examples/splitter_usage.py
Labels: BLOCKER, bug

#52 Convert to use new actions
  .github/workflows/python_actions.yml
  .travis.yml
Labels: enhancement
