Repository SpiNNakerManchester/PyNNExamples, pull requests merged in 2021-02, with the labels that each got.

#57 use moved neo_convertor
  examples/extra_models_examples/vogel_2011/vogels_2011.py
Labels: BLOCKER, enhancement

#58 added 3.9 and rat 3.8
  .github/workflows/python_actions.yml
Labels: enhancement

#60 Moved Integration test out of spynnanker
  integration_tests/README.md
  integration_tests/__init__.py
  integration_tests/script_builder.py
  integration_tests/test_scripts.py
Labels: enhancement

#61 Lost spike issues
  .github/workflows/python_actions.yml
  examples/extra_models_examples/vogel_2011/.gitignore
  examples/extra_models_examples/vogel_2011/spynnaker.cfg
Labels: enhancement

#62 remove intro_labs reference
  .github/workflows/python_actions.yml
  integration_tests/script_builder.py
Labels: bug
